spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vsite22222
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: wyhwyh222123123123123123
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maxLifetime: 1765000
      maximumPoolSize: 15

mybatis:
  mapperLocations: classpath:mapper/*.xml



